### ISSUE TITLE
main.py --> pathnet.py

### ISSUE THREAD

**Issue by alphamupsiomega** [kimhc6028/pathnet-pytorch#4]
```
Generation 99 : Fitnesses = 0.98 vs 0.975
First task done!! Move to next task
Second task started...
Traceback (most recent call last):
  File "main.py", line 258, in <module>
    main()
  File "main.py", line 189, in main
    model.init(best_path)
  File "pathnet-pytorch/pathnet.py", line 19, in init
    if best_path == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kimhc6028** [comment]
I couldn't reproduce this bug, but I modified possible bug code. Please open again if any problem appears.
